version: '3.9'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  
    ports:
      - "3000:3000"  
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db_mysql 

  db_mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: appBelleza
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
